# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
print(tensor)

tensor([[0.0468, 0.5779, 0.4138, 0.8989, 0.5380, 0.2367, 0.8935],
        [0.0164, 0.5184, 0.5675, 0.8994, 0.0703, 0.1425, 0.0635],
        [0.3987, 0.4993, 0.6099, 0.8123, 0.1409, 0.0356, 0.9304],
        [0.0531, 0.9480, 0.3606, 0.3786, 0.1961, 0.3339, 0.6953],
        [0.3272, 0.9320, 0.0635, 0.5172, 0.8916, 0.5225, 0.1431],
        [0.1999, 0.6559, 0.3060, 0.5123, 0.7958, 0.5847, 0.1664],
        [0.7567, 0.8029, 0.5986, 0.4319, 0.1040, 0.9810, 0.6454]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
print(tensor_2)
print(tensor_2.T)
# Perform matrix multiplication
tensor_3 = torch.matmul(tensor, tensor_2.T)
print(tensor_3)

tensor([[0.4689, 0.0355, 0.7015, 0.7627, 0.3931, 0.7130, 0.2446]])
tensor([[0.4689],
        [0.0355],
        [0.7015],
        [0.7627],
        [0.3931],
        [0.7130],
        [0.2446]])
tensor([[1.6172],
        [1.2550],
        [1.5605],
        [1.0855],
        [1.3835],
        [1.4928],
        [2.0309]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor = torch.rand(7,7)
tensor_2 = torch.rand(1,7)
print(tensor)
print("\n", tensor_2)
# Matrix multiply tensors
tensor_3 = torch.matmul(tensor, tensor_2.T)
print("\n",tensor_3)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
tensor_1_gpu = torch.rand(2,3, device="cuda")
tensor_2_gpu = torch.rand(2,3, device="cuda")
print("\n", tensor_1_gpu)
print("\n", tensor_2_gpu)

True

 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
tensor_matmul_gpu = torch.matmul(tensor_1_gpu, tensor_2_gpu.T)
print(tensor_matmul_gpu)
print(tensor_matmul_gpu.shape)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
print(tensor_matmul_gpu.max())

# Find min
print("\n", tensor_matmul_gpu.min())

tensor(0.7668, device='cuda:0')

 tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(tensor_matmul_gpu.argmax())

# Find arg min
print(tensor_matmul_gpu.argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
RANDOM_SEED_NEW = 10
torch.manual_seed(RANDOM_SEED_NEW)

# Create random tensor
a = torch.rand(1,1,1,10)
# Remove single dimensions
b = torch.squeeze(a, 1)

# Print out tensors and their shapes
print("Random Tensor A:", a)
print("\nRandom Tensor A Shape:",a.shape)
print("\nRemoved Single Dimensions:",b)
print("\nSqueezed Shape:",b.shape)

Random Tensor A: tensor([[[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
           0.6178, 0.3304]]]])

Random Tensor A Shape: torch.Size([1, 1, 1, 10])

Removed Single Dimensions: tensor([[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
          0.6178, 0.3304]]])

Squeezed Shape: torch.Size([1, 1, 10])
