In [36]:
import torch

In [37]:
torch.__version__
device = "cuda" if torch.cuda.is_available() else "cpu"

In [38]:
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()

0

In [39]:
torch.cuda.device(0)
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1050'

In [40]:
tensor_a = torch.randn(3,2)

tensor_b = torch.randn(3,2)

print(tensor_a)
print(tensor_b)

tensor([[-1.3627,  0.4703],
        [ 1.5763,  0.1717],
        [-0.0259, -1.5149]])
tensor([[-0.0921,  1.0765],
        [ 0.2086, -0.0109],
        [-0.3556, -1.9701]])


In [41]:
tensor_b.T, tensor_b.T.shape

(tensor([[-0.0921,  0.2086, -0.3556],
         [ 1.0765, -0.0109, -1.9701]]),
 torch.Size([2, 3]))

In [42]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 0.6318, -0.2894, -0.4420],
        [ 0.0396,  0.3269, -0.8988],
        [-1.6284,  0.0111,  2.9938]])

In [43]:
tensor_a = torch.arange(0, 100, 5)
tensor_a

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [44]:
tensor_a.min()

tensor(0)

In [45]:
tensor_a.max()

tensor(95)

In [46]:
tensor_a.type(torch.float32).mean()

tensor(47.5000)

In [47]:
tensor_a.sum(), 

(tensor(950),)

In [48]:
tensor_a.argmin(), tensor_a.argmax()

(tensor(0), tensor(19))

In [49]:
y = torch.arange(0. , 100. , 5.)
y, y.shape

(tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65.,
         70., 75., 80., 85., 90., 95.]),
 torch.Size([20]))

In [50]:
y_reshaped = y.reshape(2, 10)
y_reshaped, y_reshaped.shape

(tensor([[ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
         [50., 55., 60., 65., 70., 75., 80., 85., 90., 95.]]),
 torch.Size([2, 10]))

In [51]:
y_view = y.view(4,5)
y_view

tensor([[ 0.,  5., 10., 15., 20.],
        [25., 30., 35., 40., 45.],
        [50., 55., 60., 65., 70.],
        [75., 80., 85., 90., 95.]])

In [52]:
y_stacked = torch.stack([y, y, y, y], dim=1)
y_stacked

tensor([[ 0.,  0.,  0.,  0.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.],
        [15., 15., 15., 15.],
        [20., 20., 20., 20.],
        [25., 25., 25., 25.],
        [30., 30., 30., 30.],
        [35., 35., 35., 35.],
        [40., 40., 40., 40.],
        [45., 45., 45., 45.],
        [50., 50., 50., 50.],
        [55., 55., 55., 55.],
        [60., 60., 60., 60.],
        [65., 65., 65., 65.],
        [70., 70., 70., 70.],
        [75., 75., 75., 75.],
        [80., 80., 80., 80.],
        [85., 85., 85., 85.],
        [90., 90., 90., 90.],
        [95., 95., 95., 95.]])

In [53]:
random = torch.arange(1, 19).reshape(2, 3, 3)
random

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [54]:
random[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [55]:
random[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [56]:
random[0,1,1]

tensor(5)

In [57]:
import numpy as np

In [58]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [59]:
random_a = torch.rand(3, 4)
random_b = torch.rand(3, 4)

random_a, random_b, random_a == random_b

(tensor([[0.6353, 0.6843, 0.3816, 0.5507],
         [0.2703, 0.5834, 0.3863, 0.7409],
         [0.0038, 0.8304, 0.7796, 0.4680]]),
 tensor([[0.7003, 0.3307, 0.6014, 0.7675],
         [0.3225, 0.1543, 0.4662, 0.0722],
         [0.4665, 0.1401, 0.3090, 0.5434]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

### Random seed

In [60]:
RANDOM_SEED = 110103

torch.manual_seed(RANDOM_SEED)
random_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_d = torch.rand(3, 4)

random_c, random_d, random_c == random_d

(tensor([[0.5391, 0.9118, 0.3519, 0.5563],
         [0.2839, 0.2535, 0.2976, 0.0687],
         [0.8636, 0.4789, 0.7308, 0.1426]]),
 tensor([[0.5391, 0.9118, 0.3519, 0.5563],
         [0.2839, 0.2535, 0.2976, 0.0687],
         [0.8636, 0.4789, 0.7308, 0.1426]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [61]:
torch.cuda.is_available()

True

In [62]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [64]:
random_a, random_a.device

(tensor([[0.6353, 0.6843, 0.3816, 0.5507],
         [0.2703, 0.5834, 0.3863, 0.7409],
         [0.0038, 0.8304, 0.7796, 0.4680]]),
 device(type='cpu'))

In [66]:
random_a_new = random_a.to(device)
random_a_new.device

device(type='cuda', index=0)

In [67]:
random_a = random_a_new.cpu().numpy()
random_a

array([[0.6352906 , 0.68433064, 0.3816414 , 0.5507119 ],
       [0.27027625, 0.5833838 , 0.3863228 , 0.74087507],
       [0.00376618, 0.8303571 , 0.7795829 , 0.46798587]], dtype=float32)