In [1]:
import torch

In [2]:
torch.__version__

'2.4.0+cu124'

In [3]:
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()

0

In [4]:
torch.cuda.device(0)
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1050'

In [5]:
tensor_a = torch.randn(3,2)

tensor_b = torch.randn(3,2)

print(tensor_a)
print(tensor_b)

tensor([[ 0.4114,  0.1051],
        [-0.6147,  0.8678],
        [ 0.6357,  0.2135]])
tensor([[ 0.8183,  1.0242],
        [ 0.6418, -0.4019],
        [ 0.1938,  0.0533]])


In [6]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 0.8183,  0.6418,  0.1938],
         [ 1.0242, -0.4019,  0.0533]]),
 torch.Size([2, 3]))

In [7]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 0.4443,  0.2218,  0.0853],
        [ 0.3858, -0.7432, -0.0729],
        [ 0.7389,  0.3222,  0.1345]])

In [8]:
tensor_a = torch.arange(0, 100, 5)
tensor_a

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [9]:
tensor_a.min()

tensor(0)

In [10]:
tensor_a.max()

tensor(95)

In [11]:
tensor_a.type(torch.float32).mean()

tensor(47.5000)

In [12]:
tensor_a.sum(), 

(tensor(950),)

In [13]:
tensor_a.argmin(), tensor_a.argmax()

(tensor(0), tensor(19))

In [14]:
y = torch.arange(0. , 100. , 5.)
y, y.shape

(tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65.,
         70., 75., 80., 85., 90., 95.]),
 torch.Size([20]))

In [15]:
y_reshaped = y.reshape(2, 10)
y_reshaped, y_reshaped.shape

(tensor([[ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
         [50., 55., 60., 65., 70., 75., 80., 85., 90., 95.]]),
 torch.Size([2, 10]))

In [16]:
y_view = y.view(4,5)
y_view

tensor([[ 0.,  5., 10., 15., 20.],
        [25., 30., 35., 40., 45.],
        [50., 55., 60., 65., 70.],
        [75., 80., 85., 90., 95.]])

In [17]:
y_stacked = torch.stack([y, y, y, y], dim=1)
y_stacked

tensor([[ 0.,  0.,  0.,  0.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.],
        [15., 15., 15., 15.],
        [20., 20., 20., 20.],
        [25., 25., 25., 25.],
        [30., 30., 30., 30.],
        [35., 35., 35., 35.],
        [40., 40., 40., 40.],
        [45., 45., 45., 45.],
        [50., 50., 50., 50.],
        [55., 55., 55., 55.],
        [60., 60., 60., 60.],
        [65., 65., 65., 65.],
        [70., 70., 70., 70.],
        [75., 75., 75., 75.],
        [80., 80., 80., 80.],
        [85., 85., 85., 85.],
        [90., 90., 90., 90.],
        [95., 95., 95., 95.]])

In [18]:
random = torch.arange(1, 19).reshape(2, 3, 3)
random

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [19]:
random[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [20]:
random[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [21]:
random[0,1,1]

tensor(5)

In [22]:
import numpy as np

In [23]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)